sudo: required

install: true

services:
  - docker

language: node_js
node_js:
  - "lts/*"

before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

cache:
  directories:
    - node_modules

install:
  - npm install

after_success:
  - npm run codecov
  - docker --version
  - docker build -t helpt .
  - docker tag helpt roninen/helpt:latest
  - docker push roninen/helpt:latest
